// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "title_anim_cells.inc.c"

struct Animation anim_title_blank1[] = {
    /* 000 */ { title_cel000, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_blank2[] = {
    /* 000 */ { title_cel000, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_blank3[] = {
    /* 000 */ { title_cel000, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_blank4[] = {
    /* 000 */ { title_cel000, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_blank5[] = {
    /* 000 */ { title_cel000, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_blank6[] = {
    /* 000 */ { title_cel000, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_text[] = {
    /* 000 */ { title_cel010, 2 },
    /* 001 */ { title_cel011, 3 },
    /* 002 */ { title_cel012, 28 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_title_stars_spin[] = {
    /* 000 */ { title_cel002, 4 },
    /* 001 */ { title_cel003, 4 },
    /* 002 */ { title_cel004, 4 },
    /* 003 */ { title_cel005, 4 },
    /* 004 */ END_ANIMATION,
};

struct Animation anim_title_stars_appear[] = {
    /* 000 */ { title_cel000, 120 },
    /* 001 */ { title_cel006, 3 },
    /* 002 */ { title_cel007, 120 },
    /* 003 */ { title_cel008, 3 },
    /* 004 */ { title_cel009, 120 },
    /* 005 */ { title_cel001, 3 },
    /* 006 */ { title_cel002, 120 },
    /* 007 */ { title_cel001, 3 },
    /* 008 */ { title_cel002, 120 },
    /* 009 */ END_ANIMATION,
};

struct Animation anim_title_logo_ri[] = {
    /* 000 */ { title_cel015, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_logo_zu[] = {
    /* 000 */ { title_cel016, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_logo_mu[] = {
    /* 000 */ { title_cel017, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_logo_ten[] = {
    /* 000 */ { title_cel018, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_logo_goku[] = {
    /* 000 */ { title_cel019, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_logo_av[] = {
    /* 000 */ { title_cel100, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_logo_bubble_inner[] = {
    /* 000 */ { title_cel013, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_logo_bubble_outer[] = {
    /* 000 */ { title_cel014, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_empty[] = {
    /* 000 */ { title_cel101, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_empty_2[] = {
    /* 000 */ { title_cel103, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_logo_advance[] = {
    /* 000 */ { title_cel102, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_logo_test[] = {
    /* 000 */ { title_cel020, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_title_shooting_star[] = {
    /* 000 */ { title_cel021, 4 },
    /* 001 */ { title_cel022, 4 },
    /* 002 */ { title_cel023, 4 },
    /* 003 */ { title_cel024, 4 },
    /* 004 */ { title_cel025, 4 },
    /* 005 */ { title_cel026, 4 },
    /* 006 */ { title_cel027, 4 },
    /* 007 */ { title_cel028, 4 },
    /* 008 */ { title_cel029, 4 },
    /* 009 */ { title_cel030, 4 },
    /* 010 */ { title_cel031, 4 },
    /* 011 */ { title_cel028, 4 },
    /* 012 */ { title_cel029, 4 },
    /* 013 */ { title_cel030, 4 },
    /* 014 */ { title_cel031, 4 },
    /* 015 */ { title_cel028, 4 },
    /* 016 */ END_ANIMATION,
};

